### ISSUE TITLE
Failed to compile a for loop with a variable as a range() argument

### ISSUE THREAD

**Issue by khotkevych** [ethereum/viper#562]
This code compilation is failing with the next error message: _**"Repeat must have a nonzero positive integral number of rounds"**_.

`some_value = 4`
`for i in range(some_value):` 
`// do something`

The same situation is present if check that the value is grater than 0:

`some_value = 4`
`if some_value > 0:` 
`for i in range(some_value):` 
`// do something`

* viper Version: 0.0.2

**Comment by fubuloubu** [comment]
This is by design, we do not allow looping over variable lengths. Doing so would allow for potentially infinite gas costs, violating a major precept of Viper's design (being able to estimate gas for all functions).

While I understand this may be a hassle, we have to find other ways to enable similar functionality without violating this precept e.g. stacks/queues as list types

**Comment by khotkevych** [comment]
I think in this circumstances the error message should describe the problem better. In the example above variable satisfies the "nonzero positive" restriction.

**Comment by fubuloubu** [comment]
Totally agree on that point. That error message doesn't say anything about how it was given a variable and that's why it failed to compile.
@DavidKnott

**Comment by DavidKnott** [comment]
I'm on board with that, I'll make a PR for it.  @khotkevych Thanks a lot for making an issue!
